using GrassmannSymbolics
using Symbolics
using Test

# Two-flavor Gross-Neveu-Wilson model from Ref/2d_gn.pdf, section 3.
# The implementation follows the chiral representation in Eqs. (3.6)--(3.9)
# and the impurity definitions in Eqs. (3.50)--(3.52).  The local tensor is
# generated by symbolic Berezin integration; no closed coefficient table is
# hard-coded.

function _tfgnw_generators()
    psi = [grassmann(Symbol(:psi, f, s)) for f in 1:2, s in 1:2]
    psibar = dual.(psi)

    alpha = grassmann(:alpha, 1:2)
    beta = grassmann(:beta, 1:2)
    eta = grassmann(:eta, 1:2)
    zeta = grassmann(:zeta, 1:2)
    alphabar = dual.(alpha)
    betabar = dual.(beta)
    etabar = dual.(eta)
    zetabar = dual.(zeta)

    # Ref/2d_gn.pdf Eq. (3.12) rewrites each flavor sector as
    # dpsi1 dpsi2 dpsibar1 dpsibar2 before evaluating the two-flavor integrals.
    measure_order = GrassmannGenerator[
        psi[1, 1], psi[1, 2], psibar[1, 1], psibar[1, 2],
        psi[2, 1], psi[2, 2], psibar[2, 1], psibar[2, 2],
    ]
    legs = GrassmannGenerator[
        alpha[1], beta[1], eta[1], zeta[1],
        alpha[2], beta[2], eta[2], zeta[2],
        zetabar[1], etabar[1], betabar[1], alphabar[1],
        zetabar[2], etabar[2], betabar[2], alphabar[2],
    ]

    return (; psi, psibar, alpha, beta, eta, zeta, alphabar, betabar,
        etabar, zetabar, measure_order, legs)
end

function _tfgnw_flavor_fields(vars, f, q)
    psi = vars.psi
    psibar = vars.psibar

    phi1 = q * (psi[f, 1] + psi[f, 2])
    phi2 = q * (psi[f, 1] - psi[f, 2])
    phibar1 = q * (psibar[f, 1] + psibar[f, 2])
    phibar2 = q * (psibar[f, 1] - psibar[f, 2])

    chi1 = q * (psi[f, 1] - im * psi[f, 2])
    chi2 = q * (psi[f, 1] + im * psi[f, 2])
    chibar1 = q * (psibar[f, 1] + im * psibar[f, 2])
    chibar2 = q * (psibar[f, 1] - im * psibar[f, 2])

    return (; phi1, phi2, phibar1, phibar2, chi1, chi2, chibar1, chibar2)
end

_tfgnw_density(vars, f, s) = vars.psibar[f, s] * vars.psi[f, s]

function _tfgnw_onsite_action(vars, params)
    M1, M2, gs2, gp2, H = params.M1, params.M2, params.gs2, params.gp2, params.H
    n11 = _tfgnw_density(vars, 1, 1)
    n12 = _tfgnw_density(vars, 1, 2)
    n21 = _tfgnw_density(vars, 2, 1)
    n22 = _tfgnw_density(vars, 2, 2)

    mass_action = (M1 + 2 + im * H) * n11 + (M1 + 2 - im * H) * n12 +
        (M2 + 2 - im * H) * n21 + (M2 + 2 + im * H) * n22

    # Eq. (3.9): after the sqrt(2) renormalization, opposite chiralities carry
    # (g_sigma^2+g_pi^2)/2 and equal chiralities across flavor carry
    # (g_sigma^2-g_pi^2)/2 in exp(-S).  local_grassmann_tensor uses exp(-S),
    # so the interaction contribution enters the action with a minus sign.
    interaction_exponent = ((1 // 2) * (gs2 - gp2)) * (n11 * n21 + n12 * n22) +
        ((1 // 2) * (gs2 + gp2)) * (n11 * n12 + n21 * n22 + n11 * n22 + n21 * n12)

    return mass_action - interaction_exponent
end

function _tfgnw_bond_exponents(vars, params)
    q, z1, z2 = params.q, params.z1, params.z2
    z = (z1, z2)
    exponents = Any[]

    for f in 1:2
        fields = _tfgnw_flavor_fields(vars, f, q)
        push!(exponents, fields.phibar2 * vars.alpha[f])
        push!(exponents, -fields.phi2 * vars.alphabar[f])
        push!(exponents, fields.phibar1 * vars.betabar[f])
        push!(exponents, fields.phi1 * vars.beta[f])

        push!(exponents, z[f] * fields.chibar2 * vars.eta[f])
        push!(exponents, -z[f] * fields.chi2 * vars.etabar[f])
        push!(exponents, (1 / z[f]) * fields.chibar1 * vars.zetabar[f])
        push!(exponents, (1 / z[f]) * fields.chi1 * vars.zeta[f])
    end

    return exponents
end

function _tfgnw_base_integrand(vars, params)
    integrand = exp(-_tfgnw_onsite_action(vars, params))
    for exponent in _tfgnw_bond_exponents(vars, params)
        integrand = integrand * exp(exponent)
    end
    return integrand
end

function _tfgnw_integrate(vars, expression; simplify=true)
    tensor = integrate(expression, vars.measure_order)
    return simplify ? simplify_coefficients(tensor) : tensor
end

function _tfgnw_insertions(vars)
    n11 = _tfgnw_density(vars, 1, 1)
    n12 = _tfgnw_density(vars, 1, 2)
    n21 = _tfgnw_density(vars, 2, 1)
    n22 = _tfgnw_density(vars, 2, 2)

    chiral_condensate = n11 + n12 + n21 + n22
    pseudoscalar_singlet = im * (n11 - n12 + n21 - n22)
    pseudoscalar_triplet = im * (n11 - n12 - n21 + n22)

    return (; chiral_condensate, pseudoscalar_singlet, pseudoscalar_triplet)
end

function _tfgnw_component_tensors(vars, base)
    n11 = _tfgnw_density(vars, 1, 1)
    n12 = _tfgnw_density(vars, 1, 2)
    n21 = _tfgnw_density(vars, 2, 1)
    n22 = _tfgnw_density(vars, 2, 2)

    pure = _tfgnw_integrate(vars, base)
    s11 = _tfgnw_integrate(vars, n11 * base)
    s12 = _tfgnw_integrate(vars, n12 * base)
    s21 = _tfgnw_integrate(vars, n21 * base)
    s22 = _tfgnw_integrate(vars, n22 * base)
    return (; pure, s11, s12, s21, s22)
end

function _tfgnw_observable_tensors(components)
    chiral_condensate = simplify_coefficients(
        components.s11 + components.s12 + components.s21 + components.s22,
    )
    pseudoscalar_singlet = simplify_coefficients(
        im * (components.s11 - components.s12 + components.s21 - components.s22),
    )
    pseudoscalar_triplet = simplify_coefficients(
        im * (components.s11 - components.s12 - components.s21 + components.s22),
    )
    return (; pure=components.pure, chiral_condensate,
        pseudoscalar_singlet, pseudoscalar_triplet)
end

function derive_two_flavor_gnw_tensors()
    @variables M1 M2 gs2 gp2 H q z1 z2
    params = (; M1, M2, gs2, gp2, H, q, z1, z2)
    vars = _tfgnw_generators()
    base = _tfgnw_base_integrand(vars, params)
    insertions = _tfgnw_insertions(vars)
    components = _tfgnw_component_tensors(vars, base)
    tensors = _tfgnw_observable_tensors(components)

    return (; tensors.pure, tensors.chiral_condensate,
        tensors.pseudoscalar_singlet, tensors.pseudoscalar_triplet,
        legs=vars.legs, measure_order=vars.measure_order,
        params, vars, insertions, components)
end
# Independent transcription of the reference definitions.  The pure tensor is
# Eq. (3.9), while the impurity linear combinations are Eqs. (3.50)--(3.52).
function reference_two_flavor_gnw_tensors(derived=nothing)
    if derived !== nothing
        tensors = _tfgnw_observable_tensors(derived.components)
        return (; tensors.pure, tensors.chiral_condensate,
            tensors.pseudoscalar_singlet, tensors.pseudoscalar_triplet,
            legs=derived.legs, measure_order=derived.measure_order,
            params=derived.params, components=derived.components)
    end

    @variables M1 M2 gs2 gp2 H q z1 z2
    params = (; M1, M2, gs2, gp2, H, q, z1, z2)
    vars = _tfgnw_generators()
    base = _tfgnw_base_integrand(vars, params)
    components = _tfgnw_component_tensors(vars, base)
    tensors = _tfgnw_observable_tensors(components)

    return (; tensors.pure, tensors.chiral_condensate,
        tensors.pseudoscalar_singlet, tensors.pseudoscalar_triplet,
        legs=vars.legs, measure_order=vars.measure_order,
        params, components)
end
function two_flavor_gnw_occupation_bits(mask)
    return ntuple(k -> (mask >> (k - 1)) & 1, 16)
end

function two_flavor_gnw_occupied_legs(legs, bits)
    return GrassmannGenerator[leg for (leg, occupation) in zip(legs, bits) if occupation == 1]
end

function validate_two_flavor_gnw_tensors(; sample_masks=(0, 1, 3, 15, 255, 4095, 65535))
    derived = derive_two_flavor_gnw_tensors()
    reference = reference_two_flavor_gnw_tensors(derived)

    @test derived.legs == reference.legs
    @test derived.measure_order == reference.measure_order
    @test symbolically_equal(derived.pure, reference.pure)
    @test symbolically_equal(derived.chiral_condensate, reference.chiral_condensate)
    @test symbolically_equal(derived.pseudoscalar_singlet, reference.pseudoscalar_singlet)
    @test symbolically_equal(derived.pseudoscalar_triplet, reference.pseudoscalar_triplet)

    @test is_even(derived.pure)
    @test is_even(derived.chiral_condensate)
    @test is_even(derived.pseudoscalar_singlet)
    @test is_even(derived.pseudoscalar_triplet)

    for mask in sample_masks
        bits = two_flavor_gnw_occupation_bits(mask)
        occupied = two_flavor_gnw_occupied_legs(derived.legs, bits)
        @test symbolically_equal(
            GrassmannExpr(get_coeff(derived.pure, occupied)),
            GrassmannExpr(get_coeff(reference.pure, occupied)),
        )
        @test symbolically_equal(
            GrassmannExpr(get_coeff(derived.chiral_condensate, occupied)),
            GrassmannExpr(get_coeff(reference.chiral_condensate, occupied)),
        )
        @test symbolically_equal(
            GrassmannExpr(get_coeff(derived.pseudoscalar_singlet, occupied)),
            GrassmannExpr(get_coeff(reference.pseudoscalar_singlet, occupied)),
        )
        @test symbolically_equal(
            GrassmannExpr(get_coeff(derived.pseudoscalar_triplet, occupied)),
            GrassmannExpr(get_coeff(reference.pseudoscalar_triplet, occupied)),
        )
    end

    return derived
end

if abspath(PROGRAM_FILE) == @__FILE__
    model = validate_two_flavor_gnw_tensors()
    println("two_flavor_GNW_validation_passed")
    println("pure_terms_", length(model.pure.terms))
    println("chiral_condensate_terms_", length(model.chiral_condensate.terms))
    println("pseudoscalar_singlet_terms_", length(model.pseudoscalar_singlet.terms))
    println("pseudoscalar_triplet_terms_", length(model.pseudoscalar_triplet.terms))
end
